In [13]:
import numpy as np


In [17]:
np.array([3.2,4,6,5])
theta = np.linspace(0,np.pi,3)

Understanding Data Types in Python

In [3]:
np.array([1,2,3,4], dtype="str")

array(['1', '2', '3', '4'], dtype='<U1')

In [4]:
np.array([3,6,2,3], dtype="float32")

array([3., 6., 2., 3.], dtype=float32)

# nested lists result in multidimensional arrays

In [7]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

# Create a length-10 integer array filled with zeros

In [8]:
np.zeros(10, dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
np.zeros((5,6), dtype="float")

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# Create a 3x5 floating-point array filled with 1s

In [10]:
np.ones((4,5), dtype="float")

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# Create a 3x5 array filled with 3.14

In [11]:
np.full((4,5),3.4)

array([[3.4, 3.4, 3.4, 3.4, 3.4],
       [3.4, 3.4, 3.4, 3.4, 3.4],
       [3.4, 3.4, 3.4, 3.4, 3.4],
       [3.4, 3.4, 3.4, 3.4, 3.4]])

# Starting at 0, ending at 20, stepping by 2

In [15]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

#Now we can compute some trigonometric fuctions on these values:

In [20]:
print("theta      =", theta)
print("sin(theta)=",np.sin(theta))

theta      = [0.         1.57079633 3.14159265]
sin(theta)= [0.0000000e+00 1.0000000e+00 1.2246468e-16]
